"""add sys_location and sys_description to printers

Revision ID: 0920a68ca7c5
Revises: e396cea7bd71
Create Date: 2026-02-09 19:54:47.052649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0920a68ca7c5'
down_revision: Union[str, Sequence[str], None] = 'e396cea7bd71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sys_location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sys_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_column('sys_description')
        batch_op.drop_column('sys_location')

    # ### end Alembic commands ###
