"""replace protocol with probes

Revision ID: 79c27a1b110d
Revises: c00320d7289d
Create Date: 2026-02-08 20:52:19.844315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c27a1b110d'
down_revision: Union[str, Sequence[str], None] = 'c00320d7289d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probes', sa.JSON(), nullable=True))
        batch_op.drop_column('protocol')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocol', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('probes')

    # ### end Alembic commands ###
