"""Add printer_type_id

Revision ID: 7be52f7a848e
Revises: 7e64501348c0
Create Date: 2026-02-08 16:56:25.834335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be52f7a848e'
down_revision: Union[str, Sequence[str], None] = '7e64501348c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printers', sa.Column('printer_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'printers', 'printer_types', ['printer_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'printers', type_='foreignkey')
    op.drop_column('printers', 'printer_type_id')
    # ### end Alembic commands ###
