"""add printer logs

Revision ID: c00320d7289d
Revises: 7be52f7a848e
Create Date: 2026-02-08 20:42:25.731455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00320d7289d'
down_revision: Union[str, Sequence[str], None] = '7be52f7a848e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('printer_id', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('event_type', sa.String(), nullable=True),
        sa.Column('old_value', sa.String(), nullable=True),
        sa.Column('new_value', sa.String(), nullable=True),
        sa.Column('message', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], name='fk_printer_logs_printer_id'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('printer_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_printer_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_printers_printer_type_id', 'printer_types', ['printer_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_printers_printer_type_id', type_='foreignkey')

    op.drop_table('printer_logs')
    # ### end Alembic commands ###
