"""Initial migration

Revision ID: d2aff1559ed2
Revises: 
Create Date: 2026-02-08 11:46:23.957746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2aff1559ed2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printers_id'), 'printers', ['id'], unique=False)
    op.create_index(op.f('ix_printers_ip_address'), 'printers', ['ip_address'], unique=True)
    op.create_index(op.f('ix_printers_name'), 'printers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printers_name'), table_name='printers')
    op.drop_index(op.f('ix_printers_ip_address'), table_name='printers')
    op.drop_index(op.f('ix_printers_id'), table_name='printers')
    op.drop_table('printers')
    # ### end Alembic commands ###
