"""add last_protocol to printers

Revision ID: e396cea7bd71
Revises: 7c1d99ea1593
Create Date: 2026-02-09 16:14:48.134061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e396cea7bd71'
down_revision: Union[str, Sequence[str], None] = '7c1d99ea1593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_protocol', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_printer_printer_type', 'printer_types', ['printer_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_printer_printer_type', type_='foreignkey')
        batch_op.drop_column('last_protocol')

    # ### end Alembic commands ###
